// <auto-generated />
namespace GearShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixingCartAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingCartAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "202105171348118_FixingCartAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
